sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: cOUyRh/rHxP51v1RcAM8GwKJNVYXC/uvQhZQbH3M70GyOWzlBb2L7vRaRnA7QIy2aK164KzpgGoevlfGKLwDGpiJaLaQpHnosZBy7bBkshgUqacpLkvksy5sF2WjLrP6a+DtI4QessH0bOKYtzKavjzj+af32pB//3tGRjwjsCc=
